version: '3'

services:

  uvicorn:
    build:
      context: .
      dockerfile: Dockerfile-uvicorn-dev
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/app:/container/app
      - ./backend/migrations:/container/migrations
      - ./backend/alembic.ini:/container/alembic.ini

  postgres: 
    image: postgres:14.0-alpine
    restart: always
    # volumes: 
      # - ./backend/postgres:/var/lib/postgresql/data:rw no data save
    environment:
      POSTGRES_USER: "smp_user"
      POSTGRES_PASSWORD: "smp_password"
      POSTGRES_DB: "smp_db"
      PGDATA: "/var/lib/postgresql/data"
    ports:
        - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "81:80"